# Generated by Django 3.1.5 on 2021-02-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MA_S', models.BooleanField(default=False)),
                ('SE_S', models.BooleanField(default=False)),
                ('DE_S', models.BooleanField(default=False)),
                ('MA_NS', models.BooleanField(default=False)),
                ('SE_NS', models.BooleanField(default=False)),
                ('DE_NS', models.BooleanField(default=False)),
            ],
        ),
    ]
