# Generated by Django 3.1.5 on 2021-02-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_output_preview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='NameError',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='method',
            name='DE_NS',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='DE_S',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='MA_NS',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='MA_S',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='SE_NS',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='SE_S',
            field=models.BooleanField(default=True),
        ),
    ]
